### ISSUE TITLE
ZENODO citation

### ISSUE THREAD

**Issue by kuchaale** [demotu/detecta#1]
Hi @demotu,
can you please [make your code citable via ZENODO](https://guides.github.com/activities/citable-code/)? There are some journals not accepting your way how to cite your repository since GitHub is not considered as a [FAIR](https://www.go-fair.org/fair-principles/) compliant data repository. 

Thanks a lot

**Comment by demotu** [comment]
[![DOI](https://zenodo.org/badge/250680438.svg)](https://zenodo.org/badge/latestdoi/250680438)

Thanks.
